name: ci
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod # respects 'toolchain' directive
          check-latest: true

      # Ensure deps are there but don't rewrite files
      - name: Download modules
        run: go mod download

      - name: Vet
        run: go vet ./...

      # Build fails if module graph needs changes (read-only)
      - name: Build (read-only mod graph)
        env:
          GOFLAGS: -mod=readonly
        run: go build -v ./...
